# Generated by Django 3.0.3 on 2020-09-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Comarcal', 'Comarcal')], default='Regional', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Geometria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometria', models.CharField(choices=[('Circular', 'Circular'), ('Lineal', 'Lineal')], default='Circular', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('fechaNacimiento', models.DateField(help_text='Format: <em>DD/MM/YYYY</em>.')),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=9, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('Tierra', 'Tierra'), ('Agua', 'Agua'), ('Aire', 'Aire')], default='Tierra', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('Senderismo', 'Senderismo'), ('Trekking', 'Trekking'), ('Montañismo', 'Montañismo'), ('Alpinismo', 'Alpinismo'), ('Ciclismo', 'Ciclismo')], default='Senderismo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Alto', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('fechaNacimiento', models.DateField()),
                ('municipio', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('codPostal', models.IntegerField(max_length=5)),
                ('telefono', models.IntegerField(max_length=9)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('personaContacto', models.CharField(max_length=20)),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('tipoEntidad', models.CharField(max_length=20)),
                ('direccion', models.TextField(max_length=100)),
                ('localidad', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(max_length=9, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematica', models.CharField(choices=[('GEO', 'Geografica'), ('BIO', 'Biologica'), ('CUL', 'Cultural'), ('GEN', 'Gen'), ('EXP', 'Exp')], default='GEO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Viaje', 'Viaje'), ('Excursion', 'Excursion')], default='Viaje', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('precio', models.FloatField()),
                ('duracion', models.DurationField()),
                ('fechaSalida', models.DateField(help_text='Format: <em>DD/MM/YYYY</em>.')),
                ('fechaRecogida', models.DateField(help_text='Format: <em>DD/MM/YYYY</em>.')),
                ('lugar', models.CharField(max_length=20)),
                ('puntoPartida', models.CharField(max_length=50)),
                ('horaPartida', models.DateTimeField()),
                ('plazas', models.IntegerField()),
                ('ambito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Ambito')),
                ('geometria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Geometria')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Medio')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Modalidad')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Nivel')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Proveedor')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tematica')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tipo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.CheckConstraint(check=models.Q(precio__gte=0), name='precio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.CheckConstraint(check=models.Q(plazas__gte=0), name='plazas_gte_0'),
        ),
    ]
