# Generated by Django 3.0.3 on 2020-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ambito',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Comarcal', 'Comarcal'), ('Nacional', 'Nacional')], default='Regional', max_length=15),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='geometria',
            field=models.CharField(choices=[('Circular', 'Circular'), ('Lineal', 'Lineal')], default='Circular', max_length=15),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='medio',
            field=models.CharField(choices=[('Tierra', 'Tierra'), ('Aire', 'Aire'), ('Agua', 'Agua')], default='Tierra', max_length=10),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='modalidad',
            field=models.CharField(choices=[('Senderismo', 'Senderismo'), ('Trekking', 'Trekking'), ('Montañismo', 'Montañismo'), ('Alpinismo', 'Alpinismo'), ('Ciclismo', 'Ciclismo')], default='Senderismo', max_length=15),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nivel',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], default='Alto', max_length=10),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tematica',
            field=models.CharField(choices=[('GEO', 'Geográfica'), ('BIO', 'Biológica'), ('CUL', 'Cultural'), ('GEN', 'GEN'), ('EXP', 'EXP')], default='GEO', max_length=3),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Viaje', 'Viaje'), ('Excursion', 'Excursion')], default='Viaje', max_length=15),
        ),
        migrations.DeleteModel(
            name='Ambito',
        ),
        migrations.DeleteModel(
            name='Geometria',
        ),
        migrations.DeleteModel(
            name='Medio',
        ),
        migrations.DeleteModel(
            name='Modalidad',
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
        migrations.DeleteModel(
            name='Tematica',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
