# Generated by Django 3.0.3 on 2020-09-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200922_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'permissions': (('add_activ', 'Añadir actividad'), ('edit_activ', 'Editar actividad'), ('rem_activ', 'Eliminar actividad'))},
        ),
    ]
