# Generated by Django 3.0.3 on 2020-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200922_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ambito',
            field=models.CharField(choices=[('Regional', 'Regional'), ('Comarcal', 'Comarcal'), ('Nacional', 'Nacional')], max_length=15),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='geometria',
            field=models.CharField(choices=[('Circular', 'Circular'), ('Lineal', 'Lineal')], max_length=15),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horaPartida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='medio',
            field=models.CharField(choices=[('Tierra', 'Tierra'), ('Aire', 'Aire'), ('Agua', 'Agua')], max_length=10),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='modalidad',
            field=models.CharField(choices=[('Senderismo', 'Senderismo'), ('Trekking', 'Trekking'), ('Montañismo', 'Montañismo'), ('Alpinismo', 'Alpinismo'), ('Ciclismo', 'Ciclismo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nivel',
            field=models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tematica',
            field=models.CharField(choices=[('GEO', 'Geográfica'), ('BIO', 'Biológica'), ('CUL', 'Cultural'), ('GEN', 'GEN'), ('EXP', 'EXP')], max_length=3),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Viaje', 'Viaje'), ('Excursion', 'Excursion')], max_length=15),
        ),
    ]
