# Generated by Django 3.0.3 on 2020-09-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200922_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nivel',
            field=models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='guia',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
    ]
