# Generated by Django 3.0.3 on 2020-09-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200922_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guia',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='M', max_length=1),
        ),
    ]
