# Generated by Django 3.0.3 on 2020-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200922_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='password',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='participante',
            name='password',
            field=models.CharField(max_length=24),
        ),
    ]
